name: Docker Release PAT
on:
    push:
        branches:
            - master
        paths:
            - '.github/workflows/docker-release.yml'
            - 'lib/**'
            - '!**/maintainer.js'
            - '!**/radar.js'
            - '!**/radar-rules.js'
            - '!lib/v2/test/**'
            - '!test/**'
            - 'Dockerfile'
    workflow_dispatch: {}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/rsshub:latest
